### PR TITLE
ios Delay start fixed

### PR DESCRIPTION
**Pull request by PonnamKarthik**

### CODE REVIEW

**Comment by om-ha** [comment]
For what it's worth...

This PR fixes audio delay on iOS as confirmed by OP of this [stackoverflow question](https://stackoverflow.com/questions/59425762/flutter-audio-play-delay/).

**Comment by subhash279** [comment]
@PonnamKarthik great work! Just one thing, the playbackRate in playImmediatelyAtRate may not always be one because the user has an option to change the playbackRate. So can you pls  change it to _playbackRate which is the global variable in that file that stores the current  playbackRate. Also can you make the change of playImmediatelyAtRate in resume() function as well.

**Comment by om-ha** [comment]
Eactly. As @subhash279 said this PR does not account for playback rate.
`playImmediatelyAtRate:1.0`

Also I noticed this new change `withOptions:nil` which was `withOptions:AVAudioSessionCategoryOptionMixWithOthers`

Which could be an issue when trying to play simultaneous files via audioplayers or others.

**Comment by PonnamKarthik** [comment]
@om-ha made above-mentioned changed

**Comment by luanpotter** [comment]
Closing in lieu of #393

**Pull request closed without merging**
