### PR TITLE
Feature android x

### PR DESCRIPTION
**Pull request by I-am-original**
Hi there )
I have pushed migration to AndroidX here. Please take a look and let me know. it would be cool to merge as soon as possible ) 
Cheers

### CODE REVIEW

**Comment by erickzanardo** [comment]
Hello @I-am-original thanks for your contribution, I am not very understood about the Android X library, I will try to learn about it this week and test your changes.

**Comment by I-am-original** [comment]
Hi Eric. For now all googles plugins are migrated on AndroidX - single
replacement od Support libs. So I am forced to move also. And as I am using
AndroidX - all plugins using Support lib - conflicting. So looks like We
should also migrate to AndroidX ) to be on wave ;)

Let me know if you have any questions
Cheers

пн, 28 січ. 2019, 00:58 Erick користувач notifications@github.com пише:

**Comment by Purus** [comment]
Please accept this changes. This is required one for plugins.

**Comment by erickzanardo** [comment]
Hello @I-am-original sorry for the long delay, I tested the example app on your branch and had trouble when testing on an Android 9 emulator, the sounds simply don't play, no errors are throw though.

Have you tested on an Android 9 device? Seems to work good on Android 8.

**Comment by I-am-original** [comment]
Hi Erick. I had no chance to test it on 9.  Sorry

чт, 28 лют. 2019, 00:30 користувач Erick <notifications@github.com> пише:

**Comment by erickzanardo** [comment]
@I-am-original do you think you can take a look on it? If you get this working on Android 9, I will merge this right away :)

**Comment by I-am-original** [comment]
Hi @Eric I am afraid - this sound feature was merged before.
Here we have only AndroidX migration.

With Best Regards,
Vadym Pinchuk


пт, 1 бер. 2019 о 00:38 Erick <notifications@github.com> пише:

**Comment by I-am-original** [comment]
It would be cool to make a separate merge for that. But for now it is hard
to do. I dont have mac laptop ) and any other as well.
I have branched migration to AndroiX from that branch with feature. So here
we have different to related changes.

With Best Regards,
Vadym Pinchuk


пт, 1 бер. 2019 о 09:58 Вадим Пінчук <vad.pinchuk@gmail.com> пише:

**Comment by hugocbpassos** [comment]
@erickzanardo @luanpotter Any news?

**Comment by YamauchiEA** [comment]
Waiting for updates

**Comment by erickzanardo** [comment]
Hello, not yet, still did not had time to look into this, this is supposed to be working good, but when testing on Android 9, it did not work and had no idea why.

**Comment by erickzanardo** [comment]
hmmm, maybe these are related somehow https://github.com/luanpotter/audioplayers/issues/128

**Comment by Pebsie** [comment]
> hmmm, maybe these are related somehow #128

Running the same code on Android 9 with the example project file over one created in Android Studio worked. Not sure if that's useful.

**Comment by MarcelEdward** [comment]
an updated pubspec.yaml file seems to be missing with the new dependencies for androidX

**Comment by erickzanardo** [comment]
Took us a while to discover that the android 9 issues was not related to this, I have rebased these changes with our master and submitted a new pull request, will closing this then in favor of: https://github.com/luanpotter/audioplayers/pull/147

Thanks for your help @I-am-original

**Pull request closed without merging**
