### PR TITLE
Added boolean flag for using audioplayer for local notifications

### PR DESCRIPTION
**Pull request by I-am-original**
Hi there. For our project we need use player for notification ) and it might be useful feature for someone. 
Please let me know if you like it )

### CODE REVIEW

**Comment by erickzanardo** [comment]
Hello @I-am-original thanks for you contribution, would you mind to add a new section on the example app using this new feature, so we can test it before merging it?

**Comment by I-am-original** [comment]
Hi ) @erickzanardo easy. Will do that till the end of week
Cheers

**Comment by I-am-original** [comment]
@erickzanardo I have added some important Stuff here. Added sample to my changes. Also I have pushed update to AndroidX. Please take a look and let me know. it would be cool to merge as soon as possible ) 

Cheers

**Comment by feroult** [comment]
Hi @I-am-original thanks for contributing with audioplayers :)

I tried to run the PR branch example and I got the following messages in the console. No sound is played:

```
V/MediaPlayer(27846): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(27846): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

Is there anything that I need to do to test the feature?

**Comment by I-am-original** [comment]
Hi Eric. Actually thisfeature is about rrspecting silent ) looks like you
are muted. So this player was used to play notification sound, but, as
device is in silent mode - it is not playing.
Let me know if you have additional quedtions
Thanks

пн, 28 січ. 2019, 00:16 Fernando Ultremare користувач
notifications@github.com пише:

**Comment by I-am-original** [comment]
Sorry. Fernando ;)

пн, 28 січ. 2019, 08:31 Вадим Пінчук користувач vad.pinchuk@gmail.com пише:

**Comment by I-am-original** [comment]
Hi @feroult have you checked my PR ? Maybe you had some time for that
Thanks

**Comment by feroult** [comment]
@I-am-original Sorry for the delay... I test the notification part and it looks good on iOS. 

But on Android App I'm still getting:

```
V/MediaPlayer(19983): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(19983): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

and no sound (the phone is not in silent mode).

Also we're getting this error in the example app (both Andoird and iOS):

```
Another exception was thrown: 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 111 pos 12: 'value >= 0 && (value < length || length == 0)': is not true.
```

When I click in the advanced tab.

Would you please check it? I merged your branch with the latest master branch before testing.

**Comment by I-am-original** [comment]
Yup. Sorry I will take a look on this

чт, 14 лют. 2019, 02:49 Fernando Ultremare користувач
notifications@github.com пише:

**Comment by I-am-original** [comment]
Hi @feroult. I Have found that tabs count was not updated. sorry for that. What about sound - it is working when Ring sound is on. and silent in other way. And this logs - you have added - they appear on any tab. So it is not related isssue

**Comment by feroult** [comment]
Merged. Waiting for next release.

Thanks for you contribution @I-am-original ;)

**Comment by I-am-original** [comment]
Hey @feroult . Glad to see that ) 
There is one more PR with Breaking changes

**Pull request merged**
