### PR TITLE
[PROPOSAL] Move the Dart code to support the libraries layout

### PR DESCRIPTION
**Pull request by luanpotter**
This is the first step towards Federation. Moving dart classes around to better adhere to the libraries convention we decided on Flame.

I'm not sure what's the best place for each piece but this is my initial proposal. Consider this more of a RFC!

This is what it looks like on a more visual manner:

image

---

Things I am not sure:
* where to put web: for now, a web folder outside of `src` seems the best place for me (until we properly federate).
* "api": I invented this folder to store basically all our enums. eventually some interfaces could live there as well. I didn't want to put it inside src because in my view anyone should be able to import each enum (or api) as they need. For example, ap_web instead of having to import the AP implementation it only need to import the enums that it need. That being said I did create the ap_api.dart file outside src. So we could alternatively move the entire folder inside src, not sure.
* I intentionally did not move `PlayerControlCommand` from inside notification_service into api because eventually that will become a standalone ap_notifications module, so I am keeping it together for now.

---

How I envision the future:

* Step 1: this change.
* Step 2: migrate repo to monorepo similar to flame. Only package will be packages/ap for now
* Step 3: split into this (ap), platform interface (ap_platform_interface) and make android/darwin/web into federated packages + split all the notifications code indo ap_notifications. Now we have 6 plugins inside the `packages` folder on the monorepo.

### CODE REVIEW

**Comment by erickzanardo** [comment]
The new structure LGTM

**Comment by renancaraujo** [comment]
According to the package layout conventions, the API folder should be inside `src`. If they are meant to be used by anyone, they could be exported by a file under `lib`, ex: `lib/api.dart`. This simplifies imports for the package user.

**Comment by luanpotter** [comment]
@renancaraujo they are exported under `audioplayers_api`. I just thought might be useful to import specific enums as needed. But if it's not allowed I can change it.

**Comment by luanpotter** [comment]
Also what about web?

**Comment by renancaraujo** [comment]
> @renancaraujo they are exported under `audioplayers_api`. I just thought might be useful to import specific enums as needed. But if it's not allowed I can change it.

There is no clear advantage of importing individual files. for most cases, tree shaking and the "import show" syntax tackle possible performance and semantic problems. 


> Also what about web?

I honestly don't have strong opinions on that, I have even see people putting web code outside `lib/` (some kind of `lib_web/`).

**Comment by luanpotter** [comment]
> I honestly don't have strong opinions on that, I have even see people putting web code outside lib/ (some kind of lib_web/).

Wow, I didn't even know that was allowed haha. But then that folder gets the web code directly or does it also need its `lib_web/src` and API?

Of course when we federate web will go to another package anyway but wanted to not cause any issues.

**Pull request closed without merging**
