### PR TITLE
added buffer progress feature for android

### PR DESCRIPTION
**Pull request by hamadmarri**
I was looking to implement a buffer progress bar which is helpful sometimes when playing remote url. I have added the functionality in the audioplayers plugin(0.12.0) . It is my first time playing with a flutter plugin and I am sure my code is not good enough and need some refactoring. Also, I didn't make it as a callback or observer function, which is bad. But I made it in such a way that flutter programmer call 
`await audioPlayer.getBufferedProgress();`

and a value between 0-100 is returned; which indicates the current buffered value.

the full usage example is below: -
```
var bufferedProgress = 0;
while (bufferedProgress < 100) {
      await Future.delayed(Duration(milliseconds: 10));
      bufferedProgress = await audioPlayer.getBufferedProgress();
      debugPrint(bufferedProgress.toString());
}
bufferedProgress = 0;
```

I don't have a mac currently so I couldn't make it for ios. But I think it will be easy to add the ios code too.
I believe ios buffer listener is somehow different than android in terms of returned value. It returns array of pairs of start-end values. The easiest way is just to get the (end point) of the last pair in the array. And maybe the value of these pairs are seconds (not a percent such as android one).

### CODE REVIEW

**Comment by hamadmarri** [comment]
I have no idea how did I deleted the .gitignorer maybe when I did the patch. sorry about that

also btw, I implemented the funtion getBufferedProgress in WrappedSoundPool.java because I have to, since it extends Player. I am not sure what exactly  WrappedSoundPool class does, so I just return -11 for no reason just to implement the function.

**Comment by erickzanardo** [comment]
Hello @hamadmarri , sorry for the late response.

Would you mind implementing an example of this new feature on the example app? So we can test it and merge?

**Comment by hamadmarri** [comment]
Hello Erick,

Please see the attached file, it has linear progress bar and text widges that show buffer value. Please note that ios is not implemented. I am not sure if you really want to merge without ios implementation.


[audiotest.zip](https://github.com/luanpotter/audioplayers/files/3260487/audiotest.zip)
Thanks

**Comment by felipeespitalher** [comment]
Does anyone idea about when it'll get merged?

**Comment by phimath** [comment]
Any update on this being merged? Would really like to use this feature

**Comment by erickzanardo** [comment]
We need an example to be implemented on the example app, also we need this to be implemented on the iOS platform as well.

**Comment by bardiarastin** [comment]
this is a great feature, any updates on it?

**Comment by luanpotter** [comment]
I'm ok with not having an iOS implementation, we just need:

* add it to the example app
* make sure it doesn't explode on iOS
* fix merge conflicts

And we can put this in :)

Of course if someone is interesting in implementing this for ios/macos, feel free!

**Comment by luanpotter** [comment]
Closing this as its referencing the old Java code, we can always look at the history and port this code if we want to merge.

**Pull request closed without merging**
