### PR TITLE
Fix Android Compilation errors

### PR DESCRIPTION
**Pull request by rwrz**
Fixing the issues on #714 .
Sorry about the amount of commits, I fixed using github editing. You can rebase and squash them if needed.

### CODE REVIEW

**Comment by jinfagang** [comment]
@luanpotter Will u have a review and merge this?

**Comment by muarachmann** [comment]
@luanpotter can you have a look at this? This is quite a blocker issue on Android

**Comment by luanpotter** [comment]
This is not actually an issue, you are just using an outdated kotlin version that does not support trailing commas, etc.

I will merge this for now to unblock you but this is not the correct solution, this is back-porting the code as instead the users should upgrade kotlin. The example app is working fine on my config.

**Review by luanpotter — APPROVED** [review]
LGTM for now

**Pull request merged**
