### PR TITLE
Allow setting seek position in play function

### PR DESCRIPTION
**Pull request by rob-patchett**
Currently audio files must start playing from the beginning. This PR adds the optional functionality of setting the playback position to the `play` function (calls `seek` during player setup calling `play`).

### CODE REVIEW

**Comment by erickzanardo** [comment]
Looks good @rob-patchett , would you mind adding this feature on the example app? So we can easily test it?

**Comment by rob-patchett** [comment]
@erickzanardo absolutely, will push a commit shortly.

**Comment by rob-patchett** [comment]
@erickzanardo, added to the example app. Now the player will continue from the paused position if resumed. Cheers

**Comment by erickzanardo** [comment]
Seems to work fine on Android, @feroult would you mind test this on iOs?

**Comment by feroult** [comment]
> Seems to work fine on Android, @feroult would you mind test this on iOs?

Yes sr. I'll do it ;)

**Comment by erickzanardo** [comment]
Did the test @feroult :), everything working.

Thanks @rob-patchett

**Comment by rob-patchett** [comment]
Awesome, thanks Erick!

**Pull request merged**
