### PR TITLE
Removed warning because of deprecation of the init(image:) method in …

### LINKED ISSUE #725: Compilation warning on iOS
Hi, I'm getting a compilation warning on iOS after incorporating audioplayers 0.17.1 in my flutter app.

**Description**
I incorporated this plugin to play audio assets through AudioCache in my flutter app. I tested it in Android without any warning but when I moved to iOS I got a compilation warning which seem to be related with a deprecated method in class _MPMediaItemArtwork_. However, the app worked fine in both platforms.

**Code**
The following is the way I'm using audioplayers in my code:
```
import 'package:audioplayers/audio_cache.dart';

class _SherlockTecScaffoldState extends State<SherlockTecScaffold> with WidgetsBindingObserver {
   final ALARMA_APP_PRIMER_PLANO = "alarma_app_primer_plano.mp3";
   final reproductor = AudioCache();

   @override
   void initState() {
       super.initState();
       ...
       reproductor.load(ALARMA_APP_PRIMER_PLANO);

       Timer( Duration(seconds: 3), () {
          _traerNuevasAlarmas().then( (bandera) {
             if (bandera)
                reproductor.play(ALARMA_APP_PRIMER_PLANO);
          } );
       } );

    @override
    void dispose() {
        ...
        reproductor.clearCache();
        super.dispose();
    }

    Future<void> _generarAlertasDemo(Timer timer) async {
       ...
       reproductor.play(ALARMA_APP_PRIMER_PLANO);
    }
    ...
}
```

**Log Errors**
The output from Xcode when I compile on iOS is the following:
```
desarrollo@iMac-de-Mauro sherlock_tec % flutter run    
Downloading ios tools...                                           54.6s
Downloading ios-profile tools...                                   36.9s
Downloading ios-release tools...                                  234.8s
Launching lib/main.dart on iPhone 12 Pro in debug mode...
 
Running pod install...                                             12.6s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        13.4s
Xcode build done.                                           100.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/desarrollo/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.17.1/ios/Classes/NotificationsHandler.swift:174:75: warning:
    'init(image:)' was deprecated in iOS 10.0: Use -initWithBoundsSize:requestHandler:
                        let albumArt: MPMediaItemArtwork = MPMediaItemArtwork.init(image: artworkImage)
```

**Platforms**
- Android: worked fine.
  - OS version: Android 10
  - Device: Motorola g7 power (physical device)
  - flutter version: 1.22.4
  - audioplayers version: 0.17.1
  - App ran in debug mode.
- iOS: worked fine but I got a compilation warning.
  - OS version: iOS 14.2
  - Device: iPhone 12 Pro (simulator ran in macOS Catalina)
  - flutter version: 1.22.5
  - audioplayers version: 0.17.1
  - The app was compiled in debug and release modes.

### PR DESCRIPTION
**Pull request by rwbr**
…MPMediaItemArtwork

Fixes #725

### CODE REVIEW

**Review by luanpotter — APPROVED** [review]
Awesome!

**Comment by rwbr** [comment]
Is there any way to update the code for that pull request? The test build failed, because the deployment target of the sample app is set to iOS 9.0. The change I introduced compiles only for iOS 10 and up. So I would like to introduce a guard expression around the new code. This would make it compatible to newer iOS versions without breaking it for older versions. Or should I better issue a new pull request?

**Comment by erickzanardo** [comment]
> Is there any way to update the code for that pull request? The test build failed, because the deployment target of the sample app is set to iOS 9.0. The change I introduced compiles only for iOS 10 and up. So I would like to introduce a guard expression around the new code. This would make it compatible to newer iOS versions without breaking it for older versions. Or should I better issue a new pull request?

@rwbr tou could just make the changes and push to this PR, it is still open ;)

**Comment by rwbr** [comment]
I see, thank you @erickzanardo. I made the change on my fork and now my new commit appeared here (never did this before). I locally compiled the example with the original setting of the deployment target (iOS 9) as well as with the deployment target set to iOS 11.0. Both versions compile now.

**Review by erickzanardo — APPROVED** [review]
LGTM

**Comment by transitguide** [comment]
when will this be merged?

**Comment by transitguide** [comment]
please merge this?

**Review by luanpotter — APPROVED** [review]
LGTM

**Comment by rwbr** [comment]
Any plans to release a new version of this package with this change soon?

**Comment by erickzanardo** [comment]
> Any plans to release a new version of this package with this change soon?

0.19.1 was recently eleaed with this

**Comment by rwbr** [comment]
👍Thank's.

**Pull request merged**
