### PR TITLE
Simplify workflows, build example app apk

### PR DESCRIPTION
**Pull request by fdietze**
Since there were some android build errors in the recent PRs, I thought it would be nice to catch these automatically.
This can probably also be done for iOS.

Btw, what is the reason for the two separate workflow files here? As far as I can see, they're doing the same. Except for the triggers.

### CODE REVIEW

**Review by luanpotter — DISMISSED** [review]
One would hope running the tests would catch any errors. Thanks for this improvement @fdietze . The reason we have two is because I believe there is a difference on the first lines so that PR status don't go to the readme, but I don't recall very well, @renancaraujo would know. Sadly @wolfenrain has taught us that there is no code sharing between actions, so we got kinda stuck into copying. Maybe moving everything to a single script file and then just call it on both workflows is the solution? Not sure. either way, this LGTM

**Comment by luanpotter** [comment]
@fdietze it seems there is something wrong as the action is not run for this PR, any ideas why? I will take a look as well

**Comment by luanpotter** [comment]
@wolfenrain has been upgrading our github actions on other repos as well, would love if you could take a look!

**Comment by fdietze** [comment]
> @fdietze it seems there is something wrong as the action is not run for this PR, any ideas why? I will take a look as well

Indeed. I had a syntax error. ": " in values is not allowed in yaml.

**Comment by wolfenrain** [comment]
> @wolfenrain has been upgrading our github actions on other repos as well, would love if you could take a look!

Did a quick look, and if you are thinking of reworking the actions, I would recommend splitting it up in separate jobs(in a single file). And create fake stages.

So you have a stage for linting:
```yaml
jobs:
  dartdoc:
    ...dartdoc stuff
  
  format:
    ...format stuff

  analyze:
    ...analyze stuff
```

After that you can add a stage for testing, these jobs will then have a `needs` keyword filled with the jobs from the linting stage:
```yaml
  test:
    needs: [dartdoc, format, analyze]
    ...test stuff
```

And after that you can have your build/driver stage:
```yaml
  ios:
    needs: [test]
    ...build ios stuff
    
  android:
    needs: [test]
    ...build android stuff
    
  web:
    needs: [test, drive]
    ...build web stuff
```

This allows for quicker action fails, and allows for quick overview in github when a job fails instead of a job that fails because one of its inbetween steps failed.

**Comment by luanpotter** [comment]
@wolfenrain I love it! let me merge this and I will try to break it down like that

@fdietze I think we can do `flutter build ios --release --no-codesign`. I will merge this and try to uncomment the iOS build

**Review by luanpotter — APPROVED** [review]
LGTM

**Pull request merged**
