### PR TITLE
Added macOS support

### PR DESCRIPTION
**Pull request by balconywood**
Did a quick port of audioplayers to macOS, now that Flutter officially supports macOS in alpha. I've tested it using the example app and everything seems fine.

I had to remove a few things in the macOS implementation, like media notifications, but otherwise it's exactly the same as the iOS implementation.

### CODE REVIEW

**Comment by balconywood** [comment]
I'll look into it as soon as I can. Thanks for the quick response!

**Comment by balconywood** [comment]
I had a look at this today, and I can't find a great way to do this unfortunately. I think there'll have to be two seperate implementations for iOS and macOS.

**Comment by beevelop** [comment]
I just tested the changes on macOS and it seems to work quite smoothly. Pretty hyped about this one. Good job @balconywood 🍻

**Comment by balconywood** [comment]
Cheers @beevelop!

On the topic of the iOS and macOS implementations sharing common code @luanpotter, I've been following the porting of some of the FlutterFire plugins to macOS, and it looks like they're going to use symlinks to link to a common code file for both iOS and macOS in one of the plugins. I'm really busy at the moment but I'll see if I can implement something similar for audioplayers when I get the chance.

**Comment by balconywood** [comment]
Just added the symlinks; let me now if there's anything you'd like me to change.

**Pull request merged**
