### PR TITLE
Add kotlin-gradle-plugin at android/build.gradle

### LINKED ISSUE #718: urred evaluating project ':audioplayers'. > Plugin with id 'kotlin-android' not found.  *
```
.pub-cache\hosted\pub.flutter-io.cn\audioplayers-0.17.1\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':audioplayers'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':audioplayers'.
> compileSdkVersion is not specified. Please add it to build.gradle
```

### PR DESCRIPTION
**Pull request by koji-1009**
Thanks for the great library!

---

fix #718 

- Add `$kotlin_version` and `kotlin-gradle-plugin` at `android/build.gradle`
- Remove stdlib library from dependency block 
  - ref <https://kotlinlang.org/docs/reference/whatsnew14.html#dependency-on-the-standard-library-added-by-default>
- Update Kotlin 1.4.21
  - <https://github.com/JetBrains/kotlin/releases/tag/v1.4.21>

### CODE REVIEW

**Review by kivancg — APPROVED** [review]
LGTM

**Review by MATTYGILO — APPROVED** [review]
Looks good

**Review by MATTYGILO — APPROVED** [review]
Please approve this

**Review by erickzanardo — APPROVED** [review]

**Review by luanpotter — APPROVED** [review]
LGTM

**Comment by koji-1009** [comment]
Thanks!

**Pull request merged**
