### PR TITLE
Adding getDuration feature iOS/Android

### PR DESCRIPTION
**Pull request by alecorsino**
I have added getDuration method to get the duration after setting "setUrl" for a local file to get the duration
I have this requirement for my own project to know the duration of a local file.
I can see your code is only updating the stream with this information only when you start playing a file. I understand this if you are streaming a file form internet but if you already have the file in your own device it make sense to know the duration before playing it.

Please note that I don't need nor use audio_cache because i can see it copies to a temp dir the file i already have in my system which is not in my assets. Nevertheless i can see this class uses Audioplayer under the hood.

I haven't add tests although i tried but i think it doesn't make sense because test have a fake channel
Anyway happy to add them if you give me advice what would make sense to do in this particular case.
I added support for iOS now!

Cheers!
Ale

### CODE REVIEW

**Comment by alecorsino** [comment]
I made some changes i added iOS and Android support and created an example under Local Assets tabs.
Any chance you could please take a look?

**Comment by erickzanardo** [comment]
Hey @alecorsino thanks for your contribution, I have tested and everything is working fine.

On the Android there a lot of unnecessary changes though, I think is just formatting changes, and is a little difficult to identify which changes a related to the new feature, and which is not, would you mind reverting those changes and keeping only what is necessary to the feature?

I shall merge this right away once everything is fine! Thanks

**Comment by alecorsino** [comment]
I reverted the formatting changes. Thanks!

**Comment by erickzanardo** [comment]
Thanks!

**Pull request merged**
