### PR TITLE
Fix playing external links.

### PR DESCRIPTION
**Pull request by OperKH**
Fixes Issue #84

### CODE REVIEW

**Comment by erickzanardo** [comment]
Hello @OperKH thanks for the PR, but I am not complete sure this is how we should fix this problem, this problem seems odd because there is native code that should handle this type of situation. I will try to take a deep look on this later.

Did this problem hapen on both android and iOs?

**Comment by OperKH** [comment]
Didn't test on iOS. But this bug appears after this line have been added: `player.seek(position);`

I already provided log in my issue:
```W/MediaPlayerNative( 6375): Stream has no duration and is therefore not seekable.
E/MediaPlayerNative( 6375): error (-2147483648, 0)
E/MediaPlayerNative( 6375): Attempt to call getDuration in wrong state: mPlayer=0x8d3f2160, mCurrentState=0
E/MediaPlayerNative( 6375): error (-38, 0)```
It means that when native player plays external link (radio) it not seekable, because there is no duration on Stream.

**Comment by erickzanardo** [comment]
Yeah, for a stream it really makes no sense to seek, just to clarify, this seek was added by this [PR](https://github.com/luanpotter/audioplayers/pull/78), which is supposed to allow you play a something from an specific point.

If we check the `isLocal` variable, then when using remote music, this feature will not work, that is why I am not sure if checking the `isLocal` variable is the best way to handle this.

**Comment by OperKH** [comment]
Yep, you right.

Also I cheked iOS build. It plays audio stream, but has another issues, described here: #84

I'm not familiar with iOS develpment. May be this PR could be closed to resolve this issue in another complete PR for iOS and Android at the same time.

**Comment by erickzanardo** [comment]
@OperKH I have discussed with @luanpotter and we may have found a good solution that does not involve native development.

Instead of using the `isLocal` flag, with could change the `duration` default value from zero to null, and only calling seek with this parameter is not null. That way I think the lib will still have the desired behaviour and on the cases of music stream, you will have no problems.

I think I am able to make this change this weekend, but if you want to change this PR to the above, it would be really helpfull!

**Comment by OperKH** [comment]
OK. I'll test it tomorrow both iOS and Android and if all OK - I'll change my PR.

**Comment by OperKH** [comment]
Made changes for iOS and Android.
Also Added Radio Stream to the example.

**Comment by erickzanardo** [comment]
Hello @OperKH sorry for the delay, I was testing your changes before merging and found problems on iOs:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building PlayerWidget(dirty, state:
flutter: _PlayerWidgetState#b2600):
flutter: The getter 'inMilliseconds' was called on null.
flutter: Receiver: null
flutter: Tried calling: inMilliseconds
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
flutter: #1      _PlayerWidgetState.build (package:audioplayers_example/player_widget.dart:88:64)
flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3787:27)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:15)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #11     _invoke (dart:ui/hooks.dart:154:13)
flutter: #12     _drawFrame (dart:ui/hooks.dart:143:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
```

Works great on Android though

**Comment by OperKH** [comment]
@erickzanardo I added changes in example to fix this errors above.

**Comment by erickzanardo** [comment]
Thanks @OperKH we will try to test the master branch this week and release a new version with the fixes.

**Pull request merged**
